### PR TITLE
Fixed issue when sending message raw mime type

### LINKED ISSUE #122: Add support for sending raw mime to the API
I need to flesh this out a bit more as well...

### PR DESCRIPTION
**Pull request by arunagw**
We added support for sending raw mime type message in #169
and it stopped working after an upgrade. This PR fixes that.

This PR also fixes #122

Changes:
- Fix `Nylas::RawMessage#send!` to send raw mime type.

### CODE REVIEW

File: lib/nylas/raw_message.rb [hunk 1]
```diff
@@ -11,8 +11,12 @@ def initialize(mime_compatible_string, api:)
     end
 
     def send!
-      Message.new(api.execute(method: :post, path: "/send", payload: mime_compatible_string,
-                              headers: { "Content-type" => "message/rfc822" }).merge(api: api))
+      Message.new(**api.execute(
+        method: :post,
+        path: "/send",
+        payload: mime_compatible_string,
+        headers: { "Content-type" => "message/rfc822" }
```
Comment (adarsh) [inline lib/nylas/raw_message.rb:18]: Should this be a constant?

File: lib/nylas/raw_message.rb [hunk 2]
```diff
@@ -11,8 +11,12 @@ def initialize(mime_compatible_string, api:)
     end
 
     def send!
-      Message.new(api.execute(method: :post, path: "/send", payload: mime_compatible_string,
-                              headers: { "Content-type" => "message/rfc822" }).merge(api: api))
+      Message.new(**api.execute(
```
Comment (adarsh) [inline lib/nylas/raw_message.rb:14]: Just confirming: The only change here is the double splat, correct? The reformatting makes it a little challenging to see.

File: spec/nylas/raw_message_spec.rb [hunk 3]
```diff
@@ -0,0 +1,27 @@
...
+describe Nylas::RawMessage do
+  describe ".#send!" do
+    it "calls execute on api with params" do
+      message_string = "MIME-Version: 1.0\nContent-Type: text/plain; charset=UTF-8\n" \
+        "Subject: A mime email\n" \
+        "From: You <your-email@example.com>\n" \
+        "To: You <#{ENV.fetch('NYLAS_EXAMPLE_EMAIL', 'not-real@example.com')}>\n\n" \
+        "This is the body of the message sent as a raw mime!"
+      api = FakeAPI.new
+      # collection = Nylas::Message.new(model: FullModel, api: api)
```
Comment (adarsh) [inline spec/nylas/raw_message_spec.rb:12]: Leftover comment

**Review by adarsh — APPROVED** [review]
One leftover comment and some questions, otherwise 👍

File: lib/nylas/raw_message.rb (hunk 2 above)
Comment (arunagw) [reply lib/nylas/raw_message.rb:14]: Yes.

File: spec/nylas/raw_message_spec.rb (hunk 3 above)
Comment (arunagw) [reply spec/nylas/raw_message_spec.rb]: Thanks. Removed here f3da5928a629985fd7f434449b57e4b7f3f0c510

File: lib/nylas/raw_message.rb (hunk 1 above)
Comment (arunagw) [reply lib/nylas/raw_message.rb]: Yes for sure. Done here 54360b6c3aefa6f531d1d3554757fd4e33cd58b0
